compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

logFilters:
  - code: YN0005
    level: discard
  - code: YN0062
    level: discard

nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

enableColors: true

plugins:
  - checksum: 15431bb295e49c56c89441d8e527314cfaf1771ae8ba8bba2a0b48ae8c1b86d6a995755cb8f43e26ffc6b5ae6a39ace0a242d5f2a3e1e2ee8c17516ac307f12b
    path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/yarn-4.x-next/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.1.1.cjs
